\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename emms.info
@settitle The Emms Manual
@c %**end of header

@c Maintainer comments: As of Oct 2005 the manual is being re-written
@c for Emms2.
@c
@c As a rule, modules which are stable enough to be included into the
@c `emms-all' setup level should be documented.

@c FIXME: Stuff slated for addition to the manual:
@c emms-mode-line, emms-metaplaylist-mode.

@c FIXME: Add concept indices to all the new chapters.

@dircategory Emacs
@direntry
* Emms: (emms).           The Emacs Multimedia System
@end direntry

@copying
 @copyright{} (c) 2004, 2005
   Yoni Rabkin, Jorgen Schaefer, Mario Domgoergen
@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. A
copy of the license is included in the section entitled "GNU Free
Documentation License".
@end quotation
@end copying

@c For printed material
@titlepage
@title The Emms Manual

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents
@c END For printed material

@ifnottex
@node Top, Copying, (dir), (dir)
@top Emms Manual

This is the Manual for the Emacs Multimedia System
@c FIXME: This is the last thing that needs to be done after the
@c manual is fixed.
@menu
* Copying::             The GNU General Public License gives you permission to
                            redistribute Emms on certain terms; it also explains
                            that there is no warranty.
* The GNU FDL::         The license for this documentation.

Starting out
* Introduction::        Introduction to Emms.
* Installation::        How to install Emms on your System.
* Simple Setup::        Quick, basic default Emms setup.
* Configuration::       More detailed setup and configuration.

Emms basics
* Basic Commands::      How to control Emms with ease.
* The Core File::       The inner core of Emms.
* Sources::             Sources for playlists-creation.
* Simple Players::      Some simple players.
* Playlists::           How Emms organizes media

Advanced Features
* Info Tags::           More narrative track descriptions.
* Interactive Playlists::    Interactive Playlists.
* Extending Emms::      How to define new players and modules.
* Streaming Audio::     Interface to streaming audio.

Indices
* Concept Index::
* Function Index::
* Variable Index::
* Keybinding Index::

@c FIXME: the detailed listing needs to be re-generated after the
@c above is finished.
@detailmenu
--- The Detailed Node Listing ---

Here are some other nodes which are really inferiors of the ones
already listed, mentioned here so you can get to them in one step:

Installation
* Compiling Emms::      Compiling Emms into Byte-Code

Info Tags
* Ogg Info::    Reading ogg info tags
* mp3 Info::    Reading mp3 info tags
@end detailmenu

Extending Emms
* New Player::  How to define a new player

New Player
* Simple Player for @command{play}:: Example player using @command{play}
* More Complex Player:: Example of a complex player using @command{mpg321}
@end menu

@end ifnottex

@c including the relevant licenses
@include gpl.texi
@include fdl.texi

@node Introduction
@chapter Introduction

@cindex introduction

Emms is the Emacs Multi-Media System. It tries to be a clean and small
application to play multimedia files from Emacs using external
players. Many of its ideas are derived from MpthreePlayer
(http://www.nongnu.org/mp3player), but it tries to be more general and
more clean.

The basic functionality of Emms consists of three parts: The core, the
sources, and the players.

The core resides in @file{emms.el}, and provides a simple playlist and the
basic functionality to use all the other features of Emms. It provides
the common user commands and interfaces for other parts. It thinks in
tracks, where a track is the combination of a type and a name - e.g.
the track type 'file has a name that is the file name. Other track
types are possible.

To get to tracks, the core needs sources. The file @file{emms-source-file.el}
provides simple sources to interact with the file system.

When Emms finally has the sources in the playlist, it needs a player
to play them. @file{emms-player-simple.el} defines a few useful players, and
allows you to define your own in a very simple way.

The way Emms works is easy to customize with your own code or by using
`M-x customize'.

@node Installation
@chapter Installation

@cindex installation

You need to put all the .el files of emms in a directory in your
load-path. For example, if you put all those files into ~/elisp/emms/,
then in your ~/.emacs, you should do:

@lisp
(add-to-list 'load-path "~/elisp/emms/")
@end lisp
@noindent

@menu
* Compiling Emms::      Compiling Emms into Byte-Code
@end menu

@node Compiling Emms
@section Compiling Emms

@cindex compiling

You can byte-compile Emms by first entering the directory containing the
Emms source code, followed by invoking:

@command{make}

Which will byte compile Emms. You can then invoke:

@command{make install}

Which will install Emms into your Emacs directories (provided you have
the appropriate permissions to do so on your system).

Note that Emms is a light-weight and agile program, you can therefore
run Emms just fine without byte compiling it.

@node Simple Setup
@chapter Simple Setup

After adding the location of the Emms code to the @var{load-path}
variable, see @xref{Installation}. we invoke the following using the
`emms-setup' feature which allows for quick and simple Emms setup.

@lisp
(require 'emms-setup)
(emms-standard)
(emms-default-players)
@end lisp

After which Emms is set-up and ready to go!

The above will setup Emms with standard features (interactive
playlists, audio track tag reading etc.) and a default list of players
(ogg, mp3, mplayer etc.).

The `emms-setup' feature is provided by the file
@file{emms-setup.el}. It is essentially a collection of shortcuts for
setting up Emms quickly and simply. Everything you can do with
`emms-setup' can also be done manually.

We use `emms-setup' by calling one of the setup functions. Each of the
functions sets up Emms to include a number of features.

@defun emms-minimalistic
An Emms setup script.
Invisible playlists and all the basics for playing media.
@end defun

@defun emms-standard
An Emms setup script.
Everything included in the @code{emms-minimalistic} setup, the Emms
interactive playlist mode and reading information from tagged
audio files.
@end defun

@defun emms-all
An Emms setup script.
Everything included in the @code{emms-standard} setup and adds all the
stable features which come with the Emms distribution.
@end defun

@defun emms-devel
An Emms setup script.
Everything included in the @code{emms-all} setup and adds all of the
features which come with the Emms distribution regardless of if they
are considered stable or not.  Use this if you like living on the
edge.
@end defun

`emms-setup' also comes with a convinience function to set a default
list of media players.

@defun emms-default-players
Set @var{emms-player-list} to @var{emms-setup-default-player-list}.
@end defun

It is also worth noting that you can write your own Emms setup
functions like the above by looking at the existing function
definitions in @file{emms-setup.el}.

@node Configuration
@chapter Configuration

@cindex Configuration

This chapter discusses the configuration of Emms in more detail.

The following code fragment provides a minimal Emms setup without
using the layer of `emms-setup'. It can maybe be used to better
understand the internals of Emms. You can see how Emms needs to know
about players (these are defined in `emms-player-simple') and about
sources for tracks (trivial file system based sources, such as this
`emms-directory-tree', are defined in `emms-source-file').

@lisp
(require 'emms-player-simple)
(require 'emms-source-file)
(setq emms-player-list '(emms-player-mpg321
                         emms-player-ogg123
                         emms-player-mplayer))
@end lisp

For a discussion on how to define additional players, see @xref{Simple
Players}.

Much of the behaviour of Emms can be changed by setting
variables. For example:

@lisp
(setq emms-info-asynchronously nil)
(setq emms-playlist-buffer-name "*Music*")
@end lisp

The first @code{setq} turns off the asynchronous updating of info tags. The
second sets the default name of the Emms playlist buffer.

Another way to change Emms variables is to use the M-x
@command{customize} mechanism provided by Emacs.

@node Basic Commands
@chapter Basic Commands

@cindex basic commands
@cindex commands, basic

Before you can use the interface commands, you need a playlist to
start with. The following commands allow you to add to the current
playlist from different sources:

Note that the commands with the ``emms-add-'' prefix add the source to
the playlist but do not start playing it immediately. Conversely, the
commands with the ``emms-play-'' prefix begin playing the track
immediately.

@defun emms-play-file file
A source for a single file - either @var{file}, or queried from the
user.
@end defun
@defun emms-add-file file
A source for a single file - either @var{file}, or queried from
the user.
@end defun
@defun emms-play-directory dir
A source for a whole directory tree - either @var{dir}, or queried
from the user.
@end defun
@defun emms-add-directory dir
A source for a whole directory tree - either @var{dir}, or queried
from the user.
@end defun
@defun emms-play-directory-tree dir
A source for multiple directory trees - either @var{dir}, or the
value of @var{emms-source-file-default-directory}.
@end defun
@defun emms-add-directory-tree dir
A source for multiple directory trees - either @var{dir}, or the
value of @var{emms-source-file-default-directory}.
@end defun
@defun emms-play-url url
A source for an @var{url} - for example, for streaming.
@end defun
@defun emms-add-url url
A source for an @var{url} - for example, for streaming.
@end defun
@defun emms-play-m3u-playlist playlist
A source for the M3u playlist format from the file @var{playlist}.
@end defun
@defun emms-add-m3u-playlist playlist
A source for the M3u playlist format from the file @var{playlist}.
@end defun
@defun emms-play-find dir regexp
A source that will find files in @var{dir} or
@var{emms-source-file-default-directory} which match @var{regexp}.
@end defun
@defun emms-add-find dir regexp
A source that will find files in @var{dir} or
@var{emms-source-file-default-directory} which match @var{regexp}.
@end defun

The basic functionality of Emms is just to play music without being
noticed. It provides a few commands to skip the current track and
such, but other than that it doesn't show up. Emms provides the
following basic user commands (which you might want to bind to
keystrokes):

@defun emms-start
Start playing the current playlist
@end defun
@defun emms-stop
Stop playing
@end defun
@defun emms-next
Start playing the next track in the playlist
@end defun
@defun emms-previous
Start playing previous track in the playlist
@end defun
@defun emms-shuffle
Shuffle the current playlist. This uses
@var{emms-playlist-shuffle-function}.
@end defun
@defun emms-sort
Sort the current playlist. This uses
@var{emms-playlist-sort-function}.
@end defun
@defun emms-show &optional insertp
Describe the current Emms track in the minibuffer. If @var{insertp} is
non-nil, insert the description into the current buffer instead. This
function uses @var{emms-show-format} to format the current track.
@end defun

@node The Core File
@chapter The Core File
The core file @file{emms.el} provides the all basic functions for
playing music, generating playlists and defining players.

@menu
* User Variables::     Variables for the user to tweak.
* Hooks::              Hooks for important Emms functions.
* Core Functions::     Providing the basic functionality of Emms.
@end menu

@node User Variables
@section User Variables
The core file defines a number of user variables.

@defopt emms-player-list
A list of players Emms can use. You need to set this in order to use
Emms to play media.
@end defopt
@defopt emms-show-format
The format to use for @command{emms-show}. Any "%s" is replaced by
what @var{emms-track-description-function} returns for the currently
playing track.
@end defopt
@defopt emms-repeat-playlist
Non-nil if the Emms playlist should automatically repeat the playlist.
If nil, playback will stop when the last track finishes playing.
@end defopt
@defopt emms-track-description-function
Function for describing an Emms track in a user-friendly way.
@end defopt
@defopt emms-sort-lessp-function
A function that compares two tracks, and returns non-nil if the first
track should be sorted before the second (see also @code{sort}).
@end defopt

@node Hooks
@section Hooks
The core file provides hook variables for the basic functionality of
Emms.

@defopt emms-player-started-hook
A hook run when an Emms player started playing.
@end defopt
@defopt emms-player-stopped-hook
A hook run when an Emms player stopped playing. See also
@var{emms-player-finished-hook}.
@end defopt
@defopt emms-playlist-source-inserted-hook
Hook run when a source got inserted into the playlist. The buffer is
narrowed to the new tracks.
@end defopt
@defopt emms-playlist-selection-changed-hook
Hook run after another track is selected in the Emms playlist.
@end defopt
@defopt emms-playlist-cleared-hook
Hook run after the current Emms playlist is cleared. This happens both
when the playlist is cleared and when a new buffer is created for it.
@end defopt
@defopt emms-player-finished-hook
Hook run when an Emms player finishes playing a track. Please pay
attention to the differences between @var{emms-player-finished-hook}
and @var{emms-player-stopped-hook}. The former is called only when the
player is stopped interactively; the latter, only when the player
actually finishes playing a track.
@end defopt
@defopt emms-player-paused-hook
Hook run when a player is paused or resumed. Use
@var{emms-player-paused-p} to find the current state.
@end defopt

@node Core Functions
@section Core Functions
The core file also defines all the functions important to the basic
use of Emms.

There are functions which deal with movement in the playlist.

@defun emms-next-noerror
Start playing the next track in the Emms playlist. Unlike
@code{emms-next}, this function doesn't signal an error when called at
the end of the playlist. This function should only be called when no
player is playing. This is a good function to put in
@code{emms-player-finished-hook}.
@end defun
@defun emms-playlist-next
Move to the previous track in the current buffer.
@end defun
@defun emms-playlist-previous
Move to the previous track in the current buffer.
@end defun
@defun emms-random
Jump to a random track.
@end defun
@defun emms-toggle-repeat-playlist
Toggle whether emms repeats the playlist after it is done. See
@var{emms-repeat-playlist}.
@end defun
@defun emms-toggle-repeat-track
Toggle whether emms repeats the current track. See
@var{emms-repeat-track}.
@end defun

Some functions deal with the getting and setting track information.

@defun emms-track type name
Create a track with type @var{type} and name @var{name}.
@end defun
@defun emms-track-type track
Return the type of @var{track}.
@end defun
@defun emms-track-name track
Return the name of @var{track}.
@end defun
@defun emms-track-get name track &optional inexistent
Return the value of @var{name} for @var{track}. If there is no value,
return @var{default} (or nil, if not given).
@end defun
@defun emms-track-set track name value
Set the value of @var{name} for @var{track} to @var{value}.
@end defun
@defun emms-track-description track
Return a description of @var{track}. This function uses
@var{emms-track-description-function}.
@end defun
@defun emms-player-for track
Return an Emms player capable of playing @var{track}. This will be the
first player whose PLAYABLEP function returns non-nil, or nil if no
such player exists.
@end defun
@defun emms-playlist-current-selected-track
Return the currently selected track in the current playlist.
@end defun

There are also functions which deal with the playing itself.

@defun emms-player-start track
Start playing @var{track}.
@end defun
@defun emms-player-stop
Stop the currently playing player.
@end defun
@defun emms-player-stopped
Declare that the current Emms player is finished.
This should only be done by the current player itself.
@end defun
@defun emms-seek seconds
Seek the current player @var{seconds} seconds. This can be a floating
point number for sub-second fractions. It can also be negative to
seek backwards.
@end defun
@defun emms-seek-forward
Seek ten seconds forward.
@end defun
@defun emms-seek-backward
Seek ten seconds backward.
@end defun

For more basic commands defined in the core file see @xref{Basic
Commands}.

@node Sources
@chapter Sources

@cindex Sources

Sources allow Emms to add and play tracks. Emms comes with a number of
sources of its own. Sources are designed so that creating new ones
will be easy.

For examples of Emms sources for files and directories see
@file{emms-source-file.el}.

@defopt emms-source-file-default-directory
The default directory to look for media files.
@end defopt
@defun emms-play-find
Play all files in @var{emms-source-file-default-directory} that match
a specific regular expression.
@end defun
@defun emms-source-file &optional file
An Emms source for a single file - either @var{file}, or queried from the
user.
@end defun
@defun emms-source-files files
An Emms source for a list of @var{files}.
@end defun
@defun emms-source-directory &optional dir
An Emms source for a whole directory tree - either @var{dir}, or queried
from the user
@end defun
@defun emms-source-directory-tree & optional dir
An Emms source for multiple directory trees - either @var{dir}, or the
value of @var{emms-source-file-default-directory}.
@end defun
@defun emms-source-find &optional dir regex
An Emms source that will find files in @var{dir} or
@var{emms-source-file-default-directory} that match @var{regexp}.
@end defun
@defun emms-source-file-directory-tree &optional dir
Return a list of all files under @var{dir} which match @var{regex}.
@end defun
@defun emms-source-dired
Play all marked files of a dired buffer
@end defun
@defun emms-source-file-regex
Return a regexp that matches everything any player (that supports
files) can play.
@end defun
@defun emms-locate regexp
Search for @var{regexp} and display the results in a locate buffer
@end defun

@node Simple Players
@chapter Simple Players

@cindex players, simple

@defmac define-emms-simple-player name types regex command &rest args
Define a simple player with the use of `emms-define-player'.
@var{name} is used to contruct the name of the function like
emms-player-@var{name}. @var{types} is a list of track types
understood by this player. @var{regex} must be a regexp that matches
the filenames the player can play. @var{command} specifies the command
line arguement to call the player and @var{args} are the command line
arguements.
@end defmac

For a discussion on how to define new players see @xref{New Player}.

@defun emms-player-simple-stop
Stop the currently playing process, if indeed there is one.
@end defun
@defun emms-player-simple-start filename cmdname params
Starts a process playing @var{filename} using the specified @var{cmdname} with
the specified @var{params}.
@end defun
@defun emms-player-simple-sentinel proc str
Sentinel for determining the end of process for the process @var{proc}
and the sentinel string @var{str}.
@end defun

@node Playlists
@chapter Playlists

@cindex organizing tracks and media

Emms uses Emacs buffers to store the media tracks for playing. We call
one such buffer a ``playlist buffer'' or an ``Emms playlist
buffer''. Emms then proceeds to play the media tracks in the buffer
from top to bottom until the end of the playlist.

The name of the playlist buffer is defined in the variable
@var{emms-playlist-buffer-name} and is set to be an invisible Emacs
buffer by default. You can change to any name you want. For an example
configuration see @xref{Configuration}.

You can create any number of playlist buffers you wish. At any time
Emms has a single ``current'' buffer through which it proceeds track
by track.

@defun emms-playlist-new &optional name
Create a new playlist buffer.
The buffer is named @var{name}, but made unique. @var{name} defaults
to `emms-playlist-buffer-name'. If called interactively, the new
buffer is also selected.
@end defun

The current Emms playlist buffer is stored in the variable
@var{emms-playlist-buffer}.

@c FIXME: Needs to be fixe-up
@node Info Tags
@chapter Info Tags

@cindex track information

To create a method for retrieving (or setting) info about a file, you
create an object like this:

@lisp
(define-emms-info-method emms-info-mp3info
  :providep 'emms-info-mp3info-providep
  :get 'emms-info-mp3info-get
  :set 'emms-info-mp3info-set)
@end lisp

Then you register it with emms-info, by adding it to
@var{emms-info-methods-list}.

If you wish to use 'emms-info-mp3info' you will need the mp3info
program which is available at http://www.ibiblio.org/mp3info/.
Otherwise Emms will display an error when you attempt to access mp3
info.

@lisp
(add-to-list 'emms-info-methods-list 'emms-info-mp3info)
@end lisp
@noindent

Emms is distributed with two predefined methods for retrieving
info. These and all other methods for retrieving info from media
tracks are managed by the `emms-info' feature defined in the file
@file{emms-info.el}.

@menu
* Ogg Info::    Reading Ogg info tags
* mp3 Info::    Reading mp3 info tags
@end menu

There are a number of user variables which control the behaviour of
`emms-info'.

@defopt emms-info-auto-update
Non-nil when Emms should update track information if the file changes.
This will cause hard drive activity on track loading. If this is too
annoying for you, set this variable to nil.
@end defopt
@defopt emms-info-asynchronously
Non-nil when track information should be loaded asynchronously. This
requires the feature `later-do' which is provided by the file
@file{later-do.el}, which should come with Emms.
@end defopt
@defopt emms-info-functions
Functions which add information to tracks.  Each is called with a
track as argument.
@end defopt

@c FIXME: update this to emms-info-ogginfo.el
@node Ogg Info
@section Ogg Info
The file @file{emms-info-ogg.el} provides an interface to retrieving
comments from ogg-files, using Lawrence Mitchells ogg-comment.el.

To activate, put something like this in your ~/.emacs:

@lisp
(require 'emms-info-ogg)
(add-to-list 'emms-player-alist
             '("\\.ogg$" . emms-info-ogg-comments))
@end lisp
@noindent

Of course, you'll also need a player if you want to actually play the
files.

@defun emms-info-ogg-comment-providep
Return non-nil if this info-method provides info for the track.
@end defun
@defun emms-info-ogg-get-comment
@end defun
@defun emms-info-ogg-comment-get
Retrieve an emms-info structure as an ogg-comment
@end defun

@c FIXME: update this for the latest version of mp3info
@node mp3 Info
@section mp3 Info

This code has been adapted from code found in mp3player.el, written by
Jean-Philippe Theberge @email{jphiltheberge@@videotron.ca}, Mario Domgoergen
@email{kanaldrache@@gmx.de} and Jorgen Schäfer @email{forcer@@forcix.cx}

To activate this method for getting info, use something like:

@lisp
(require 'emms-info-mp3info)
(add-to-list 'emms-info-methods-alist
             '("\\.mp3$" . emms-info-mp3info))
@end lisp
@noindent

Of course, you'll also need a player if you want to actually play the
files.

@defun emms-info-mp3info-providep
Return non-nil if this info-method provides info for the track.
@end defun
@defun emms-info-mp3info-set track info
Set the id3v1 tag of file @var{track} to id3info @var{info}, using the
@var{mp3info-program}.
@end defun
@defun emms-info-mp3info-get track
Get the id3v1 tag of file @var{track}, using the mp3info-program and
return an emms-info structure representing it.
@end defun

@defopt emms-info-mp3info-program-name
*The name/path of the mp3info-program.
@end defopt

@node Interactive Playlists
@chapter Interactive Playlists
@cindex Interactive Playlists

@c FIXME: Completely rewrite the playlist buffer thus introducing the
@c concept of multiple playlists to the people.

@node Extending Emms
@chapter Extending Emms

@cindex new players
@cindex defining players
@cindex new players, defining

Emms introduces a high abstraction layer for playing music so you can
customise a lot of things to morph Emms into @emph{your} media player.
@c FIXME: Compress this into a smaller footprint, no need for so many
@c submenus.
@menu
* New Player::  How to define a new player
@end menu

@node New Player
@section New Player

The file @file{emms-player-simple.el} defines some easy players to
start with, but it shouldn't be hard to provide a function for your
favourite player. We will start with an easy example that shows how
we can use the @command{play} command under Unix to play our WAV files.

@menu
* Simple Player for @command{play}:: An example player using @command{play}
* More Complex Player:: Example of a complex player using @command{mpg321}
@end menu

@node Simple Player for @command{play}
@subsection Simple Player for @command{play}

Play is a very easy command line player for various format. If you
want your emms to play WAV files just put the following lines in you
@file{.emacs}:

@lisp
(require 'emms-player-simple)
(define-emms-simple-player play '(file) "\\.wav$" "play")
@end lisp
@noindent

Huh! Wasn't that easy?

The macro function @command{define-emms-simple-player} takes a minimum
of three arguments. The first argument (@emph{play} in our example)
defines the name of the player. It's used to name the player
functions. The second is a regexp, that defines which files to play
with our player. @emph{\\.wav$} matches any filename ending with a dot
and the string wav. The last argument is the actual command line
command we use to play our files. You can also add the path but we
just assume that the command is in your path. All arguments you add to
these three are optional. They define the command line arguments you
want to add to your argument. If you want to hear the wav file of
your favourite artist in the most possible volume use the following
line:

@lisp
(require 'emms-player-simple)
(define-emms-simple-player play '(file) "\\artist-*.wav$" "play" "--volume=100")
@end lisp
@noindent

Please notice that you have to add the arguments as strings!

The command line tool you use for @command{define-emms-simple-player}
has to take one song as argument and stop after playing that
particular song. For any other concept you will need to customise
emms a bit more...

@node More Complex Player
@subsection More Complex Player

The most players you use will be simple players so you don't need to
read this chapter. But if you are curious how you can use (almost) every
player in emms read further...

In this chapter we will use mpg321 to construct a player that
actually can pause a track, restart it and show rest time. We won't
implement all of that, but after that chapter you will know how to
define it.

The command @command{define-emms-simple-player} is just a abstraction
layer for @command{define-emms-player}, which is a little bit more
complicated but much more powerful!

@lisp
(define-emms-player "emms-mpg321-remote"
  :start 'emms-mpg321-remote-start
  :stop 'emms-mpg321-remote-stop
  :playablep 'emms-mpg321-remote-playable-p)
@end lisp
@noindent

So, that almost all! @command{define-emms-player} takes a minimum of
three arguments. The first is the name of the player. The rest are
methods with functions to call. Three methods are required: start,
stop and playable. Start says Emms how to start a track (sic!), stop
how to stop a player and playablep should return non-nil if the
player can play the track.

So we just need these three functions to get our mpg321-remote:

First we code the start function. We will check if there's a open
process and start one otherwise. Then we send a string to the process
with the filename and set a filter.

@lisp
(defun emms-mpg321-remote-start ()
  (unless (get-process "mpg321-remote")
    (setq emms-mpg321-remote-process
	  (start-process "mpg321-remote-process"
			 "*mpg321*" "mpg321" "-R" "abc"))
  (process-send-string "mpg321-remote-process"
		       (concat "l " (emms-track-name track)))
  (set-process-filter emms-mpg321-remote-process 'emms-mpg321-remote-filter)))
@end lisp
@noindent

We need the filter, as mpg321-remote won't quit after playing the
track as the simple player do. We wait until the process send the
output ``@@P 0'' (the signal of mpg321 that the song ended) to the
filter and call emms-mpg321-remote-stop.

@lisp
(defun emms-mpg321-remote-filter (process output)
  (when (string-match "@@P 0" output)
    (emms-mpg321-remote-stop)))
@end lisp
@noindent

@command{emms-mpg321-remote-stop} won't do anything interesting. It
just test if there are other files to play and close the process otherwise.

@lisp
(defun emms-mpg321-remote-stop ()
  (unless emms-playlist
    (process-send-string "mpg321-remote-process" "Q\n"))
@end lisp
@noindent

And to make that a playable example i also added
@command{emms-mpg321-remote-playablep}, which i just really steal
from @file{emms-player-simple.el}

@lisp
(defun emms-mpg321-remote-playablep (track)
       "Return non-nil when we can play this track."
       (and (eq 'file (emms-track-type track))
@end lisp
@noindent

Now we have a ready player and we could add commands like
@command{emms-mpg321-remote-pause} for example.

@node Streaming Audio
@chapter Streaming Audio

@cindex streaming audio
@cindex internet radio

Emms provides a friendly interface for managing and playing streaming
audio in addition to the Emms playlist interface. The interface is
defined in the @file{emms-streams.el} package and can be loaded by
invoking:

@lisp
(require 'emms-streams)
@end lisp

Enter the emms-streams interface by invoking M-x
@command{emms-streams}. The emms-streams interface comes with a
built-in, eclectic list of streaming audio channels from thoughout the
Web. Emms can of-course play other streams than the ones listed by
default, you are free to remove any or all of them and add your
own.@footnote{If you enjoy a particular streaming audio station on the
Web and think that it belongs in the default list, please send us a
link and we will gladly add it!}

The following is a list of the key-bindings for the emms-streams
interface:

@table @kbd
@item RET
@kindex RET (emms-streams)
@vindex emms-stream-default-action
Perform the default action when you press RET in the Emms Stream
interface. Can be either ``add'' or ``play''. The default is ``add'',
which adds the station under point to the Emms playlist. When
@var{emms-stream-default-action} is ``play'' then Emms will play the
streaming audio channel under point.
@item q
@kindex q (emms-streams)
@findex emms-stream-quit
Quit the emms-streams interface.
@item a
@kindex a (emms-streams)
@findex emms-stream-add-bookmark
Add a bookmark to a streaming audio URL to the list.
@item d
@kindex d (emms-streams)
@findex emms-stream-delete-bookmark
Remove a bookmark to a streaming audio URL from the list.
@item e
@kindex e (emms-streams)
@findex emms-stream-edit-bookmark
Edit the details of the bookmark under point.
@item h
@kindex h (emms-streams)
@findex describe-mode
Describe the emms-streams mode.
@item n
@kindex n (emms-streams)
@findex emms-stream-next-line
Move to the next line in the emms-streams buffer (same as C-n).
@item p
@kindex p (emms-streams)
@findex emms-stream-previous-line
Move to the previous line in the emms-streams buffer (same as C-p).
@item s
@kindex s (emms-streams)
@findex emms-stream-save-bookmarks-file
Save the bookmarks in the emms-streams interface to disk. The
bookmarks will be to the location designated in the variable
@var{emms-stream-bookmarks-file}.
@item i
@kindex i (emms-streams)
@findex emms-stream-info-bookmark
Return information about the streaming audio at the URL of the
bookmark under point. Note that this will only work if the
`emms-stream-info' has already been loaded.
@end table

@node Concept Index
@unnumbered Concept Index
@printindex cp

@node Function Index
@unnumbered Function Index
@printindex fn

@node Variable Index
@unnumbered Variable Index
@printindex vr

@node Keybinding Index
@unnumbered Keybinding Index
@printindex ky

@bye
